import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ width: "33%", height: 200, position: "relative" }}>
        <Image
          layout="fill"
          objectFit="cover"
          src={
            "https://images.ctfassets.net/rx7wswrhto2v/HIfkJkImtDL4BYMrkpJxy/63a13e823543168200127d87266abd96/IMG_4492.jpg"
          }
          alt=""
          sizes={"(max-width: 640px) 100vw, 25vw"}
        />
      </div>
    </div>
  );
};

export default Home;
